import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@heroui/react";
import HeroProvider from "../../HeroProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroProvider>{children}</HeroProvider>
      </body>
    </html>
  );
}
import { AuthProvider } from "@/context/authContext";
// bọc children:
<AuthProvider>{children}</AuthProvider>
NEXT_PUBLIC_BACKEND_URL= "https://duomath.onrender.com"