"""
build_colab_notebook.py - Tạo file notebook Jupyter .ipynb hoàn chỉnh cho Qwen2.5-VL Optimization Suite
Dựa trên D:\qwen_vl_optimization_guide.pdf
"""
import json
from pathlib import Path

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 Qwen2.5-VL Hình Học: Trọn bộ Tối ưu Huấn luyện & Đánh giá (DuoMath Suite)\n",
                "> **Tham chiếu kế hoạch:** `D:\\qwen_vl_optimization_guide.pdf`\n",
                "\n",
                "Notebook này được thiết kế **chống mất dữ liệu (Auto-backup Drive/HuggingFace)** và tích hợp trọn vẹn **6 hướng tối ưu**:\n",
                "1. **Chuẩn hoá định dạng đáp án cuối** (`Dap an cuoi cung:`)\n",
                "2. **Tự động tải & mở rộng dữ liệu** (`geo170k` + `geometry3k` từ Hugging Face)\n",
                "3. **Huấn luyện LoRA Unsloth 4-bit** (siêu tốc, tiết kiệm VRAM trên GPU T4/A100)\n",
                "4. **Đánh giá Benchmark toàn diện**, phân rã theo nguồn dữ liệu\n",
                "5. **Self-Consistency suy luận** (Vote đa số)\n",
                "6. **GRPO Reinforcement Learning** sau SFT\n",
                "7. **Gộp trọng số sạch FP16** (Tránh bẫy double quantization)\n",
                "\n",
                "*(Nếu Colab vừa reset: Bạn có thể chọn **Tùy chọn A** để nạp thẳng model đã train sẵn từ Hugging Face `WilliamShakespear/duomath-qwen-vl-lora`, hoặc **Tùy chọn B** để chạy chu trình mở rộng mới.)*"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 1. KIỂM TRA GPU & CÀI ĐẶT THƯ VIỆN\n",
                "# ==============================================================================\n",
                "!nvidia-smi\n",
                "\n",
                "import os\n",
                "print(\"\\n[INFO] Đang cài đặt Unsloth và các thư viện cần thiết...\")\n",
                "!pip install --no-deps \"unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git\"\n",
                "!pip install --no-deps trl peft accelerate bitsandbytes datasets torchvision pillow"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 2. KẾT NỐI GOOGLE DRIVE (CHỐNG MẤT DỮ LIỆU KHI COLAB RESET)\n",
                "# ==============================================================================\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n",
                "\n",
                "import os\n",
                "DRIVE_BACKUP_DIR = \"/content/drive/MyDrive/DuoMath_QwenVL_Checkpoints\"\n",
                "os.makedirs(DRIVE_BACKUP_DIR, exist_ok=True)\n",
                "print(f\"Thư mục lưu trữ an toàn trên Google Drive: {DRIVE_BACKUP_DIR}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 3. CHUẨN HOÁ FORMAT ĐÁP ÁN & CÔNG CỤ CHẤM ĐIỂM (Mục 1 trong Guide)\n",
                "# ==============================================================================\n",
                "import re\n",
                "\n",
                "FINAL_ANSWER_TAG = \"Dap an cuoi cung:\"\n",
                "\n",
                "SYSTEM_PROMPT = (\n",
                "    \"You are a careful geometry tutor. Reason step by step about the shapes, \"\n",
                "    \"coordinates, and relationships shown in the diagram, then on the LAST line \"\n",
                "    \"write exactly:\\n\"\n",
                "    f\"{FINAL_ANSWER_TAG} <answer>\\n\"\n",
                "    \"with nothing else after it.\"\n",
                ")\n",
                "\n",
                "def extract_final_answer(text: str) -> str:\n",
                "    if not text:\n",
                "        return \"\"\n",
                "    if FINAL_ANSWER_TAG in text:\n",
                "        return text.rsplit(FINAL_ANSWER_TAG, 1)[-1].strip().split(\"\\n\")[0].strip()\n",
                "    patterns = [\n",
                "        r\"the (?:final )?answer is\\s*[:=]?\\s*([^\\n\\.]+)\",\n",
                "        r\"correct (?:choice|option|answer) is\\s*[:=]?\\s*([^\\n\\.]+)\",\n",
                "        r\"(?:đáp án|kết quả) (?:là|cuối cùng là)\\s*[:=]?\\s*([^\\n\\.]+)\",\n",
                "        r\"\\\\boxed{([^}]+)}\"\n",
                "    ]\n",
                "    for p in patterns:\n",
                "        m = re.findall(p, text, re.IGNORECASE)\n",
                "        if m:\n",
                "            return m[-1].strip()\n",
                "    return text[-150:].strip()\n",
                "\n",
                "def grade(prediction: str, gold: str) -> bool:\n",
                "    if not prediction or not gold:\n",
                "        return False\n",
                "    pred_raw = extract_final_answer(prediction)\n",
                "    p_clean = re.sub(r\"^\\$+|\\$+$|\\\\text\\{|\\}\", \"\", pred_raw).strip().lower()\n",
                "    g_clean = re.sub(r\"^\\$+|\\$+$|\\\\text\\{|\\}\", \"\", str(gold)).strip().lower()\n",
                "    if p_clean == g_clean:\n",
                "        return True\n",
                "    if bool(re.fullmatch(r\"[a-f]\", g_clean)):\n",
                "        m = re.search(r\"\\b([a-f])\\b\", p_clean)\n",
                "        if m and m.group(1) == g_clean:\n",
                "            return True\n",
                "    try:\n",
                "        p_num = float(re.sub(r\"[^\\d\\.\\-]\", \"\", p_clean))\n",
                "        g_num = float(re.sub(r\"[^\\d\\.\\-]\", \"\", g_clean))\n",
                "        if abs(p_num - g_num) < 1e-4 or (abs(g_num) > 0 and abs(p_num - g_num) / abs(g_num) < 1e-3):\n",
                "            return True\n",
                "    except Exception:\n",
                "        pass\n",
                "    return False\n",
                "\n",
                "print(\"Module Chuẩn hoá Prompt & Hàm chấm điểm grade() đã sẵn sàng!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 🎯 BẠN CÓ 2 LỰA CHỌN TẠI ĐÂY:\n",
                "- **Lựa chọn A (Tiết kiệm thời gian, KHÔNG CẦN TRAIN LẠI):** Nạp lại thẳng checkpoint đã lưu trên Hugging Face (`WilliamShakespear/duomath-qwen-vl-lora`) để chạy ngay Đánh giá Benchmark / Self-Consistency hoặc train tiếp GRPO.\n",
                "- **Lựa chọn B (Chạy chu trình mới toàn diện):** Tự động tải dữ liệu mở rộng (`geo170k` + `geometry3k`) và SFT lại từ đầu."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# LỰA CHỌN A: NẠP LẠI CHECKPOINT TỪ HUGGING FACE (MẤT ~30 GIÂY, KHÔNG TRAIN LẠI)\n",
                "# ==============================================================================\n",
                "LOAD_FROM_HF_CHECKPOINT = True  # Đổi thành False nếu muốn train lại từ đầu theo Lựa chọn B\n",
                "\n",
                "from unsloth import FastVisionModel\n",
                "import torch\n",
                "\n",
                "if LOAD_FROM_HF_CHECKPOINT:\n",
                "    HF_REPO = \"WilliamShakespear/duomath-qwen-vl-lora\"\n",
                "    print(f\"[INFO] Đang kéo checkpoint đã train từ Hugging Face: {HF_REPO}...\")\n",
                "    model, tokenizer = FastVisionModel.from_pretrained(\n",
                "        model_name=HF_REPO,\n",
                "        load_in_4bit=True,\n",
                "    )\n",
                "    print(\"✅ Checkpoint đã sẵn sàng trong GPU! Bạn có thể nhảy ngay đến Cell Benchmark (Mục 5) hoặc GRPO (Mục 2).\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# LỰA CHỌN B: TỰ ĐỘNG TẢI DỮ LIỆU MỞ RỘNG (Mục 4: geo170k + geometry3k)\n",
                "# ==============================================================================\n",
                "# Chỉ chạy cell này nếu bạn muốn mở rộng dataset và train SFT lại\n",
                "import json, random\n",
                "from pathlib import Path\n",
                "from datasets import load_dataset\n",
                "from PIL import Image\n",
                "\n",
                "IMG_DIR = Path(\"data/images\")\n",
                "PROCESSED_DIR = Path(\"data/processed\")\n",
                "IMG_DIR.mkdir(parents=True, exist_ok=True)\n",
                "PROCESSED_DIR.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                "def resize_max_side(img, max_side=1024):\n",
                "    w, h = img.size\n",
                "    if max(w, h) <= max_side:\n",
                "        return img\n",
                "    scale = max_side / max(w, h)\n",
                "    return img.resize((int(w * scale), int(h * scale)), Image.Resampling.LANCZOS)\n",
                "\n",
                "GEO_CONFIGS = [\"geo170k(qa)\", \"geometry3k(mathv360k)\"]\n",
                "MAX_PER_CONFIG = 3000\n",
                "train_records = []\n",
                "\n",
                "print(\"[INFO] Đang tải dữ liệu trực tiếp từ lmms-lab/LLaVA-OneVision-Data về Colab...\")\n",
                "for cfg in GEO_CONFIGS:\n",
                "    print(f\"Tải: {cfg}...\")\n",
                "    try:\n",
                "        ds = load_dataset(\"lmms-lab/LLaVA-OneVision-Data\", cfg, split=f\"train[:{MAX_PER_CONFIG}]\")\n",
                "        for i, row in enumerate(ds):\n",
                "            if row.get(\"image\") is None:\n",
                "                continue\n",
                "            convs = row.get(\"conversations\") or []\n",
                "            h_turns = [c[\"value\"] for c in convs if c.get(\"from\") == \"human\"]\n",
                "            g_turns = [c[\"value\"] for c in convs if c.get(\"from\") == \"gpt\"]\n",
                "            if not h_turns or not g_turns:\n",
                "                continue\n",
                "            q = h_turns[0].replace(\"<image>\", \"\").strip()\n",
                "            ans = g_turns[-1].strip()\n",
                "            prefix = cfg.split('(')[0]\n",
                "            dst_name = f\"{prefix}_{row.get('id', i)}.png\"\n",
                "            dst_file = IMG_DIR / dst_name\n",
                "            if not dst_file.exists():\n",
                "                resize_max_side(row[\"image\"].convert(\"RGB\")).save(dst_file)\n",
                "            train_records.append({\n",
                "                \"id\": f\"{cfg}_{row.get('id', i)}\",\n",
                "                \"dataset_source\": cfg,\n",
                "                \"image\": dst_name,\n",
                "                \"question\": q,\n",
                "                \"answer\": ans\n",
                "            })\n",
                "    except Exception as e:\n",
                "        print(f\"Lỗi tải {cfg}: {e}\")\n",
                "\n",
                "random.Random(42).shuffle(train_records)\n",
                "n_val = max(1, int(len(train_records) * 0.05))\n",
                "train_set, val_set = train_records[n_val:], train_records[:n_val]\n",
                "\n",
                "def save_jsonl(path, items):\n",
                "    with open(path, \"w\", encoding=\"utf-8\") as f:\n",
                "        for it in items:\n",
                "            f.write(json.dumps(it, ensure_ascii=False) + \"\\n\")\n",
                "\n",
                "save_jsonl(PROCESSED_DIR / \"train.jsonl\", train_set)\n",
                "save_jsonl(PROCESSED_DIR / \"test.jsonl\", val_set) # Dùng val_set làm test benchmark\n",
                "print(f\"✅ Đã chuẩn bị xong: Train={len(train_set)} mẫu, Test={len(val_set)} mẫu!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 4. ĐÁNH GIÁ BENCHMARK TOÀN DIỆN TÁCH THEO NGUỒN (Mục 5 trong Guide)\n",
                "# ==============================================================================\n",
                "from collections import defaultdict\n",
                "from PIL import Image\n",
                "\n",
                "FastVisionModel.for_inference(model)\n",
                "\n",
                "def load_jsonl(filepath):\n",
                "    with open(filepath, \"r\", encoding=\"utf-8\") as f:\n",
                "        return [json.loads(line) for line in f if line.strip()]\n",
                "\n",
                "test_file = PROCESSED_DIR / \"test.jsonl\"\n",
                "test_data = load_jsonl(test_file)\n",
                "stats = defaultdict(lambda: [0, 0])\n",
                "\n",
                "print(f\"[INFO] Đang chạy Benchmark trên toàn bộ {len(test_data)} mẫu test...\")\n",
                "for idx, r in enumerate(test_data, 1):\n",
                "    img_p = IMG_DIR / r[\"image\"]\n",
                "    if not img_p.exists():\n",
                "        continue\n",
                "    img = Image.open(img_p).convert(\"RGB\")\n",
                "    messages = [\n",
                "        {\"role\": \"system\", \"content\": [{\"type\": \"text\", \"text\": SYSTEM_PROMPT}]},\n",
                "        {\"role\": \"user\", \"content\": [{\"type\": \"image\"}, {\"type\": \"text\", \"text\": r[\"question\"]}]},\n",
                "    ]\n",
                "    input_text = tokenizer.apply_chat_template(messages, add_generation_prompt=True)\n",
                "    inputs = tokenizer(img, input_text, add_special_tokens=False, return_tensors=\"pt\").to(\"cuda\")\n",
                "    output_ids = model.generate(**inputs, max_new_tokens=512, use_cache=True, temperature=0.2, min_p=0.1)\n",
                "    output_text = tokenizer.decode(output_ids[0][inputs[\"input_ids\"].shape[1]:], skip_special_tokens=True)\n",
                "    \n",
                "    is_correct = grade(output_text, str(r[\"answer\"]))\n",
                "    src = r.get(\"dataset_source\", \"chung\")\n",
                "    stats[src][1] += 1\n",
                "    stats[src][0] += int(is_correct)\n",
                "\n",
                "print(\"\\n\" + \"=\" * 45)\n",
                "print(f\"{'Nguon':<16} {'Dung':>6} {'Tong':>6} {'Ty le':>10}\")\n",
                "print(\"-\" * 45)\n",
                "for src, (c, t) in stats.items():\n",
                "    print(f\"{src:<16} {c:>6} {t:>6} {c/t*100:>9.1f}%\")\n",
                "oc, ot = sum(c for c, t in stats.values()), sum(t for c, t in stats.values())\n",
                "print(\"-\" * 45)\n",
                "print(f\"{'TONG CONG':<16} {oc:>6} {ot:>6} {oc/ot*100:>9.1f}%\")\n",
                "print(\"=\" * 45)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 5. SELF-CONSISTENCY VOTE ĐA SỐ (Mục 3: Thử nghiệm không cần train lại)\n",
                "# ==============================================================================\n",
                "from collections import Counter\n",
                "\n",
                "def self_consistency_solve(image, question, n_samples=5, temperature=0.7):\n",
                "    messages = [\n",
                "        {\"role\": \"system\", \"content\": [{\"type\": \"text\", \"text\": SYSTEM_PROMPT}]},\n",
                "        {\"role\": \"user\", \"content\": [{\"type\": \"image\"}, {\"type\": \"text\", \"text\": question}]},\n",
                "    ]\n",
                "    input_text = tokenizer.apply_chat_template(messages, add_generation_prompt=True)\n",
                "    inputs = tokenizer(image, input_text, add_special_tokens=False, return_tensors=\"pt\").to(\"cuda\")\n",
                "    votes = []\n",
                "    for _ in range(n_samples):\n",
                "        output_ids = model.generate(\n",
                "            **inputs, max_new_tokens=512, use_cache=True,\n",
                "            temperature=temperature, min_p=0.1, do_sample=True\n",
                "        )\n",
                "        text = tokenizer.decode(output_ids[0][inputs[\"input_ids\"].shape[1]:], skip_special_tokens=True)\n",
                "        votes.append(extract_final_answer(text))\n",
                "    best_ans, count = Counter(votes).most_common(1)[0]\n",
                "    return best_ans, votes\n",
                "\n",
                "print(\"Hàm self_consistency_solve() đã sẵn sàng để kiểm thử!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 6. HUẤN LUYỆN GRPO RL SAU SFT (Mục 2 trong Guide)\n",
                "# ==============================================================================\n",
                "from trl import GRPOConfig, GRPOTrainer\n",
                "\n",
                "def to_grpo_prompt(sample):\n",
                "    img_path = IMG_DIR / sample[\"image\"]\n",
                "    if not img_path.exists():\n",
                "        return None\n",
                "    try:\n",
                "        image = Image.open(img_path).convert(\"RGB\")\n",
                "    except Exception:\n",
                "        return None\n",
                "    return {\n",
                "        \"prompt\": [\n",
                "            {\"role\": \"system\", \"content\": [{\"type\": \"text\", \"text\": SYSTEM_PROMPT}]},\n",
                "            {\"role\": \"user\", \"content\": [{\"type\": \"image\", \"image\": image}, {\"type\": \"text\", \"text\": sample[\"question\"]}]},\n",
                "        ],\n",
                "        \"answer\": sample[\"answer\"],\n",
                "    }\n",
                "\n",
                "grpo_raw = load_jsonl(PROCESSED_DIR / \"train.jsonl\")\n",
                "# Chạy thử nghiệm trên 30-50 mẫu để xác nhận độ ổn định VRAM\n",
                "grpo_dataset = [g for g in (to_grpo_prompt(s) for s in grpo_raw[:50]) if g is not None]\n",
                "\n",
                "def accuracy_reward(completions, answer, **kwargs):\n",
                "    rewards = []\n",
                "    for comp, gold in zip(completions, answer):\n",
                "        text = comp[0][\"content\"] if isinstance(comp, list) else comp\n",
                "        rewards.append(1.0 if grade(text, str(gold)) else 0.0)\n",
                "    return rewards\n",
                "\n",
                "FastVisionModel.for_training(model)\n",
                "\n",
                "grpo_config = GRPOConfig(\n",
                "    output_dir=\"outputs_grpo\",\n",
                "    per_device_train_batch_size=1,\n",
                "    gradient_accumulation_steps=4,\n",
                "    num_generations=4,\n",
                "    max_completion_length=512,\n",
                "    learning_rate=1e-5,\n",
                "    logging_steps=1,\n",
                "    save_strategy=\"steps\",\n",
                "    save_steps=20,\n",
                "    report_to=\"none\",\n",
                ")\n",
                "\n",
                "grpo_trainer = GRPOTrainer(\n",
                "    model=model,\n",
                "    reward_funcs=accuracy_reward,\n",
                "    args=grpo_config,\n",
                "    train_dataset=grpo_dataset,\n",
                ")\n",
                "\n",
                "print(\"[INFO] Bắt đầu huấn luyện GRPO RL...\")\n",
                "grpo_trainer.train()\n",
                "print(\"✅ Hoàn tất GRPO Training!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ==============================================================================\n",
                "# 7. SAU KHI TRAIN XONG: LƯU TỰ ĐỘNG VÀO GOOGLE DRIVE & HUGGING FACE\n",
                "# ==============================================================================\n",
                "# Lưu vào Google Drive (chống mất mát vĩnh viễn):\n",
                "model.save_pretrained(f\"{DRIVE_BACKUP_DIR}/duomath_qwen_vl_lora_final\")\n",
                "tokenizer.save_pretrained(f\"{DRIVE_BACKUP_DIR}/duomath_qwen_vl_lora_final\")\n",
                "print(f\"✅ Đã lưu an toàn vào Google Drive: {DRIVE_BACKUP_DIR}/duomath_qwen_vl_lora_final\")\n",
                "\n",
                "# Đẩy lên Hugging Face Hub (thay hf_token của bạn):\n",
                "# model.push_to_hub(\"WilliamShakespear/duomath-qwen-vl-lora\", token=\"YOUR_HF_TOKEN\")\n",
                "# tokenizer.push_to_hub(\"WilliamShakespear/duomath-qwen-vl-lora\", token=\"YOUR_HF_TOKEN\")"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "provenance": []
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

out_path = Path("c:/Users/Latitude 7300/OneDrive/Máy tính/duosteam - Copy/duosteam/backend/training/Qwen2_5_VL_Geometry_Optimization_Suite.ipynb")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"Created notebook at: {out_path}")
